basePath: /
host: localhost:8000
info:
  contact:
    email: wesleybruno.so@gmail.com
    name: Wesley Oliveira
    url: https://www.linkedin.com/in/wesley-oliveira-/
  description: Product API with auhtentication
  termsOfService: http://swagger.io/terms/
  title: Go Expert Course - API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
